gpu: 0
experiment_root: ${oc.env:FTGSPP_RUNS_ROOT,runs}/${data.name}
output_path: ${run.experiment_root}/run_${train.iterations}
log_dir: ${oc.env:FTGSPP_LOG_DIR,runs/logs}
export_filename: gaussians_4dgs.ply
overwrite_completed: false
